### ISSUE TITLE
core/workflow-testing

### ISSUE THREAD

**Issue by rwx-yxu** [advweb-grp1/advanced-web-final-year-project#21] opened 2023-03-22 00:55 UTC
Modify github actions to run cypress and vitest. We currently don't have any tests at the moment so this is low priority.

**Comment by LiamSingh64** [comment] 2023-03-25 22:28
I will add a dummy test for Cypress (e2e) and Vitest (unit-testing) in the appropriate locations, probably just the example ones given from the course slides.

I will then run them just from the terminal to make sure they work as intended, and add the command to run these tests to the Workflow.

More useful tests can later be added to the test scripts.

**Comment by LiamSingh64** [comment] 2023-03-25 22:41
Project already has example tests to run

e2e tests are run with `npm run test:e2e` and Unit Tests are run with `npm run test:unit`

**Comment by LiamSingh64** [comment] 2023-03-25 22:54
vitest.config.js had wrong path to import vite.config.js, don't know why, fixed it but not sure if that will mess anything up when the code gets merged and you guys try running it? Like, I don't know if that was just an error on my machine?

**Comment by LiamSingh64** [comment] 2023-03-25 22:57
Commands to run tests work as expected, now just need to add these to the Actions Workflow

**Comment by LiamSingh64** [comment] 2023-03-25 23:22
Not sure if there is a certain way of adding more commands and I've never used .yaml before so I just appended the run test commands after the `npm run build` command.

**Comment by LiamSingh64** [comment] 2023-03-25 23:55
#23 PR Opened and workflow ran successfully, just waiting for any reviewers comments

**Closed** 2023-04-06 10:02 UTC
Labels: good first issue
